### PR TITLE
118 bytes + optional attribution (IANAL)

### PR DESCRIPTION
**Pull request by landfillbaby**
How do you feel about this?
I did some research and this *should* be just as good legally.

### CODE REVIEW

**Comment by landfillbaby** [comment]
feel free to only incorporate parts of this btw

**Comment by r-lyeh** [comment]
Hello landfillbaby. I've reviewed the changes you made. Is the text you included coming from any published & approved license? Bc  the main point of this repo is to provide a license, whose texts and clauses are made of previously approved licenses :D

**Comment by landfillbaby** [comment]
oh sorry, if you look at the first of the 2 commits, it's the same as it previously was but with a few words removed. that's the one i meant to put in this PR. the 2nd commit is kind of a joke honestly. copyright isn't real

**Comment by r-lyeh** [comment]
Yeah, I think your intentions are good and the rephrasal is not that bad! However, I cannot merge your changes (I'm sticking to unmodified texts from previously approved licenses for now :D) I encourage you to fork and/or create a new repo with your new shiny license on it, though. Maybe it will be popular someday! Freedom at best! :D

**Comment by r-lyeh** [comment]
ps: sorry for not merging! :o)

**Comment by landfillbaby** [comment]
that's fine :) i already did open my own repo actually

**Pull request closed without merging**
